In [4]:
import numpy as np
arr_1 = np.array([1, 2, 3, 4, 5])
print(arr_1)
print(type(arr_1))
print(arr_1.shape)
print(arr_1.ndim)
print(arr_1.dtype)
print(arr_1.size)

arr_2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr_2)
print(type(arr_2))
print(arr_2.shape)
print(arr_2.ndim)
print(arr_2.dtype)
print(arr_2.size)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1
int64
5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
(2, 5)
2
int64
10


In [ ]:
#Reshaping arrays
import numpy as np
array_3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(array_3)
print(array_3.shape)
# reshaped_array = array_3.reshape(5, 3)
# reshaped_array = array_3.reshape(15,) #1 row and 15 columns - single []
# reshaped_array = array_3.reshape(1,15) #1 row and 15 columns - double [[]] why there is a difference between single and double brackets?
reshaped_array = array_3.reshape(15, 1) #15 rows and 1 column
# reshaped_array = array_3.reshape(, 15) #Invalid. error
print(reshaped_array)
print(reshaped_array.shape) 
print(reshaped_array.ndim) 
print(reshaped_array.dtype)

In [ ]:
## Slicing arrays
array_4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# print(array_4[-2:0:-1]) #slicing in reverse order
print(array_4[0:5:2]) #slicing with step size of 2
print(array_4[-2:]) #slicing from the second last element to the end
print(array_4[:5]) #slicing from the beginning to the fifth element

[1 3 5]
[ 9 10]
[1 2 3 4 5]


In [ ]:
## Methods to create an array fast
np.zeros((3, 4)) #creates an array of zeros with 3 rows and 4 columns

np.ones((2, 5)) #creates an array of ones with 2 rows and 5 columns

np.arange(0, 10, 2) #creates an array of numbers from 0 to 10 with a step size of 2

np.linspace(0, 1, 5) #creates an array of 5 evenly spaced numbers between 0 and 1
np.linspace(0, 10, num=5) #creates an array of 5 evenly spaced numbers between 0 and 10 - same as


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [46]:
## Adding and sorting elements in an numpy array
array_4 = np.array([1, 42, 37, 54, 15, 6, 71, 28, 9, 91])
print(np.sort(array_4)) #sorts the array in ascending order
np.sort(array_4) #sorts the array in ascending order

np.sort(array_4)[0] #returns the smallest element in the array
np.sort(array_4)[-1] #returns the largest element in the array

np.sort(array_4)[::-1] #sorts the array in descending order
np.sort(array_4)[::-2] #sorts the array in descending order and returns every second element

[ 1  6  9 15 28 37 42 54 71 91]


array([91, 54, 37, 15,  6])

In [ ]:
## Adding and concatenating arrays
array_5 = np.array([[1, 2],[3,4]])
array_6 = np.array([[5, 6],[7,8]])

print("Original arrays:")
print("array_5:")
print(array_5)
print("-------")
print("array_6:")
print(array_6)
print("-------")
print(np.concatenate((array_5, array_6), axis=0)) #concatenates the arrays along the rows
print("-------")
print(np.concatenate((array_5, array_6), axis=1)) #concatenates the arrays along the columns
print("-------")
print(np.concatenate((array_5, array_6), axis=None)) #concatenates the arrays into a single array
print("-------")
print(np.concatenate((array_5, array_6), axis=-1)) #concatenates the arrays along the last axis (same as axis=1 for 2D arrays)
print("-------")
# print(np.concatenate((array_5, array_6), axis=2)) #Invalid. error because the arrays are 2D and we are trying to concatenate along the third axis which does not exist
# print("-------")
print(np.concatenate((array_5, array_6), axis=-2)) #concatenates the arrays along the second last axis (same as axis=0 for 2D arrays)


In [64]:
## Basic arithmetic operations on arrays
array_7 = np.array([1, 2, 3, 4, 5])
array_8 = np.array([6, 7, 8, 9, 10])
print("Original arrays:")
print("array_7:")
print(array_7)
print("array_8:")
print(array_8)  
print("-------")
print("Addition:")
print(array_7 + array_8) #element-wise addition
print("-------")
print("Subtraction:")
print(array_7 - array_8) #element-wise subtraction
print("-------")
print("Multiplication:")
print(array_7 * array_8) #element-wise multiplication
print("-------")
print("Division:")
print(array_7 / array_8) #element-wise division


Original arrays:
array_7:
[1 2 3 4 5]
array_8:
[ 6  7  8  9 10]
-------
Addition:
[ 7  9 11 13 15]
-------
Subtraction:
[-5 -5 -5 -5 -5]
-------
Multiplication:
[ 6 14 24 36 50]
-------
Division:
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
## summing elements in an array
array_9 = np.array([1, 2, 3, 4, 5])
print("Original array:") 
print(array_9)
print("Sum of elements in the array:")
print(np.sum(array_9)) #sums all the elements in the array

#Minimum and maximum elements in an array
print("Minimum element in the array:")
print(np.min(array_9)) #returns the minimum element in the array
print("Maximum element in the array:")
print(np.max(array_9)) #returns the maximum element in the array

#Mean and median of an array
print("Mean of elements in the array:")
print(np.mean(array_9)) #returns the mean of all elements in the array
print("Median of elements in the array:")
print(np.median(array_9)) #returns the median of all elements in the array

#broadcasting in numpy
array_10 = np.array([1, 2, 3, 4, 5])
print("Original array:")    
print(array_10)
print("Array after broadcasting:")  
print(array_10 + 10) #broadcasts the scalar value 10 to each element in the array and adds it to each element
print(array_10 * 2) #broadcasts the scalar value 2 to each element in the array and multiplies it with each element
print(array_10 / 2) #broadcasts the scalar value 2 to each element in the array and divides each element by 2
print(array_10 - 1) #broadcasts the scalar value 1 to each element in the array and subtracts it from each element
print(array_10 ** 2) #broadcasts the scalar value 2 to each element in the array and raises each element to the power of 2
print(array_10 % 2) #broadcasts the scalar value 2 to each element in the array and returns the remainder of each element when divided by 2
print(array_10 // 2) #broadcasts the scalar value 2 to each element in the array and returns the floor division of each element by 2

In [ ]:
#filtering elements in an array
array_11 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original array:")
print(array_11)
print("Filtered array (elements greater than 5):")
print(array_11 > 5) #returns a boolean array where each element is True if the condition is met and False otherwise
print(array_11[array_11 > 5]) #filters the array and returns only the elements that are greater than 5

print(array_11[array_11 <= 7])

#filetering by multiple conditions
print(array_11[(array_11 > 3) & (array_11 < 8)]) #filters the array and returns only the elements that are greater than 3 and less than 8
print(array_11[(array_11 < 3) | (array_11 > 8)]) #filters the array and returns only the elements that are less than 3 or greater than 8


In [78]:
## How to save and load numpy arrays
array_12 = np.array([1, 2, 3, 4, 5])
np.save('array_12.npy', array_12) #saves the array to a file named 'array_12.npy'
loaded_array_12 = np.load('array_12.npy') #loads the array from the
print("Loaded array:")
print(loaded_array_12)
loaded_array_12

#Saving the array in a text file
np.savetxt('array_12.txt', array_12) #saves the array to a text file named 'array_12.txt'
loaded_array_12_txt = np.loadtxt('array_12.txt') #loads the array from the text file
print("Loaded array from text file:")   

print(loaded_array_12_txt)

Loaded array:
[1 2 3 4 5]
Loaded array from text file:
[1. 2. 3. 4. 5.]
