In [ ]:
import numpy as np
array_1 = np.array([[26, 1, 4], [0,0,6], [0,2,8],[0,3,2]])
array_2 = np.ones((4,3), dtype=int)*2
print("-----------")
print(array_1)
print("-----------")
print(array_2)
print("-----------")
array_3 = array_1 + array_2 + 10
print(array_3)

array_4 = np.ones((4,3), dtype=int)*5
array_5 = np.ones((1,3), dtype=int)*2

print("-----------")
print(array_4)

print("-----------")
print(array_5)

print("-----------")
array_6 = array_4 * array_5
print(array_6)

In [15]:
import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning)

In [1]:
import numpy as np
nparr1 = np.array([1,2,3,4,5])

print("ndim:", nparr1.ndim)
print("shape:", nparr1.shape) 
print("size:", nparr1.size)
print("dtype:", nparr1.dtype)

nparr2 = np.array(
    [
        [1,2,3,4,5], 
        [7,8,9,10,11], 
        [12,13,14,15,16]
        ])
print("-----------")
print("ndim:", nparr2.ndim)
print("shape:", nparr2.shape)
print("size:", nparr2.size)
print("dtype:", nparr2.dtype)

print("Reshaped array:")
print(nparr2.reshape(-1, 5)) ##



ndim: 1
shape: (5,)
size: 5
dtype: int64
-----------
ndim: 2
shape: (3, 5)
size: 15
dtype: int64
Reshaped array:
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]


In [ ]:
nparr3 = np.full((3,4), fill_value=7) # Create a 3x4 array filled with the value 7
print("-----------")
print(nparr3)

nparr4 = np.eye(4) # Create a 4x4 identity matrix, which has 1s on the diagonal and 0s elsewhere
print("-----------")
print(nparr4)

nparr5 = np.random.rand(2,3) # Create a 2x3 array filled with random values between 0 and 1
print("-----------")    
print(nparr5)

nparr6 = np.random.randint(1, 10, size=(3,4)) # Create a 3x4 array filled with random integers between 1 and 9
print("-----------") 
print(nparr6)

nparr7 = np.arange(0, 20, 2) # Create a 1D array with values from 0 to 19, with a step of 2
print("-----------")
print(nparr7)

nparr8 = np.diag([1, 2, 3, 4]) # Create a 4x4 diagonal matrix with the specified values on the diagonal
print("-----------")
print(nparr8)

nparr9 = np.zeros((2,5)) # Create a 2x5 array filled with zeros
print("-----------")
print(nparr9)   



In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[10, 20, 30]])
print("-----------")
print(a+b)

-----------
[[11 22 33]
 [14 25 36]]


In [3]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(array)


[1 2 3 4 5]


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [4]:
# eye function - creates a 2D array where 1 will be diagonal elements and rest will be 0's. size of the array will be nxn
nparr1 = np.eye(4)
print(nparr1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
