030126 - NumPy Practice Problems

In [117]:
## Numpy-MCQ1 - What will be the shape of the following NumPy array?
import numpy as np
from numpy.ma.extras import column_stack

arr = np.random.randint(1, 101, 100).reshape(10, -1)
print(arr.shape)


(10, 10)


In [119]:
## Numpy-MCQ2 - What is the result of the following code?

import numpy as np
A = np.array([1, 2, 3])
B = A * 2
print(B)

[2 4 6]


In [120]:
## Numpy-MCQ3: What does the following code output?

import numpy as np
matrix = np.eye(4)
result = np.diagonal(matrix)
print(result)

#np.eye() function generates an identity matrix with ones on the diagonal elements and zeros elsewhere.
#np.diagonal(0 function extracts the diagonal elements from the matrix given


[1. 1. 1. 1.]


In [ ]:
## Numpy-MCQ4: What is the result of the following code?

import numpy as np
A = np.array([[1, 2], [3, 4]])
B = A.T ### .T on an numpy array does a transpose
## alternatively you could use np.transpose(A)

print(B)

In [121]:
## Numpy-MCQ5: Which function can be used to concatenate two NumPy arrays horizontally?

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

np.hstack((arr1,arr2))  ## This is the IK answer

## I think these two functions also works same. not sure what the difference and why these are not the answers
#np.append(arr1,arr2)
#arr3=np.concatenate((arr1,arr2),axis=0)
#print(arr3)

## Also note vstack function for vertical stacking
#np.vstack((arr1,arr2))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [123]:
## Numpy-MCQ6: Which of the following functions can be used to compute the element-wise multiplication of two arrays A and B?

'''This is the answer'''
np.multiply(arr1, arr2) ## This is the answer
##OR you could also use A*B

## Also check other function related to multiplication
#np.dot(arr1, arr2) ## this computes the dot product of two arrays

#np.matmul(arr1,arr2) ## this is matrix multiplication, similar to .dot product but difference are there., check docs - check wikipedia search "Matrix Multiplication"

#np.inner(arr1, arr2)

array([ 5, 12, 21, 32])

In [124]:
## Numpy-MCQ7: What is the result of the following code?
import numpy as np
A = np.array([10, 20, 30, 40])
mask = (A >= 20) & (A <= 30)

B = A[mask]
print(B)

#Answer will be [20,30]

[20 30]


In [ ]:
## Numpy-MCQ8: Which of the following NumPy functions will return the indices of the minimum and maximum values in an array?

##Answer is np.argmin(), np.argmax()

#np.where() is another function, this gives the index based on a condition


In [125]:
## Numpy-MCQ9: What is the output of the following code?

import numpy as np

arr = np.arange(1, 10).reshape(3, 3)

## above code. creates an arrary with values ranging from 1-10 excluding 10, so 1 through 9. reshapes into 3 by 3 array.

result = np.trace(arr) # trace of an array is the sum of diagonal elements. so the answer is 1+5+9 = 15

print(result)

15


In [61]:
## Numpy-MCQ10: What is the output of the following code?
## Instructor help - listen
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# .cross() - is a cross product.
result = np.cross(arr1, arr2)
print(result)

[-3  6 -3]


In [127]:
## Numpy-FF1: Write a Python program using NumPy to create a 5x5 matrix filled with random integers between 1 and 100. Calculate the mean and standard deviation of the matrix and print them.

import numpy as np

#self
#nparr1 = np.random.randint(1,101,25).reshape(5,-1)

#alternative method - instructor
nparr1 = np.random.randint(1,101, size=(5,5))
print(nparr1)
print("standard deviation:", nparr1.std())
print("mean:",nparr1.mean())

[[53  7 72 97  7]
 [57 73 58 34 36]
 [22 68 57 90 95]
 [19 73 29 97 95]
 [53 10 28 23 36]]
standard deviation: 29.256219851511915
mean: 51.56


In [130]:
## Numpy-FF2: Using NumPy, create a 5x5 identity matrix and add a scalar value of 5 to it. Multiply the resulting matrix with a 5x1 column vector filled with random integers between 1 and 10. Print the resulting vector.

import numpy as np
narr1 = np.identity(5)

#narr2 = np.random.randint(1,10,5).reshape(5,1)

# better approach than above
narr2 = np.random.randint(1,11, size=(5,1))

print(narr1)
print("-------")
print(narr2)

result = (narr1 + 5) * narr2

print(result)




[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
-------
[[6]
 [3]
 [1]
 [7]
 [2]]
[[36. 30. 30. 30. 30.]
 [15. 18. 15. 15. 15.]
 [ 5.  5.  6.  5.  5.]
 [35. 35. 35. 42. 35.]
 [10. 10. 10. 10. 12.]]


In [132]:
## Numpy-FF3: Write a Python program using NumPy to create two 3x3 matrices filled with random integers between 1 and 100. Compute their element-wise multiplication, and print the resulting matrix.

#arr1 = np.random.randint(1,101,9).reshape(3,3)

arr1 = np.random.randint(1,101, size=(3,3))
arr2 = np.random.randint(1,101, size=(3,3))

result = np.multiply(arr1, arr2) ## OR result = arr1 * arr2 is also correct.

print(result)


[[1944 3705  153]
 [1012 1898  119]
 [1350 5440 2867]]


In [133]:
## Numpy-FF4: Using NumPy, create a 1000-element array of random integers between 1 and 1000. Calculate the cumulative sum of the array and print the 10th, 100th, and 500th elements of the cumulative sum array.

arr1000 = np.random.randint(1,1001,1000)
#arr1000 = np.random.randint(1,1001,size=(1000,)) # both are same

print("Sum: ", np.sum(arr1000))
cumArr1000 = np.cumsum(arr1000)
#print("Cumulative Sum: ", cumArr1000)
print("10th element of cumulative sum array:", cumArr1000[9])
print("100th element of cumulative sum array:", cumArr1000[99])
print("500th element of cumulative sum array:", cumArr1000[499])


Sum:  509959
10th element of cumulative sum array: 5053
100th element of cumulative sum array: 52512
500th element of cumulative sum array: 260098


In [137]:
## Numpy-FF5: Write a Python program using NumPy to create a 10x10 matrix filled with random integers between 1 and 100. Find the minimum and maximum values of the matrix along with their indices.

#arr10 = np.random.randint(1,101,100).reshape(10,10)
# OR
arr10 = np.random.randint(1,101,size=(10,10))

print(arr10)
print(f"Min value of the matrix is {np.min(arr10)} and is at {np.argmin(arr10)} th position")
print(f"Max value of the matrix is {np.max(arr10)} and is at {np.argmax(arr10)} th position")

#argmin gives only the single index linear index. this solution doesn't work very well with 2D arrays/matrix

'''Better solution is subclass'''
min_val_idx = np.argmin(arr10)
max_val_idx = np.argmax(arr10)

##Unravel - provides the coordinates of value provides
min_idx = np.unravel_index(min_val_idx, arr10.shape)
max_idx = np.unravel_index(max_val_idx, arr10.shape)

print(min_idx, max_idx)






[[41 49 85 75 41 52  8 40  6 58]
 [26 41 11 48 72 34 77 88 21 22]
 [61 93 37 60 64 31 86 82 43 47]
 [85 58  8 92 30 68 37 87 71  3]
 [27  4 81 20 79 64 76 86 47 72]
 [93 83 84 18  1 66 49 77 25 56]
 [47 88 58 54 30 69 47 57 71 87]
 [79 22 69 87 81 83 62 25 97 32]
 [86 48 10 31 83 49 84 95  3  1]
 [74 33 49 96 67 90 56 29 13 18]]
Min value of the matrix is 1 and is at 54 th position
Max value of the matrix is 97 and is at 78 th position
(np.int64(5), np.int64(4)) (np.int64(7), np.int64(8))


In [142]:
## Numpy-FF6: Write a Python program using NumPy to create a 5x5 matrix filled with random floats between 0 and 1. Replace the maximum value in the matrix with 0 and print the original and modified matrices.

''' check this again......'''
#arrf5 = np.random.rand(5,5).reshape(1,-1)
arrf5 = np.random.random(size=(5,5))

# print(arrf5.size)
# print(arrf5.shape)

#max_index = np.unravel_index((np.argmax(arrf5)))
print(arrf5)
maxIdx = np.argmax(arrf5)

print(maxIdx)
arrf5[0,maxIdx] = 0

print(arrf5.reshape(5,5))
#use the  unravel ---

max_val = np.max(arrf5)

arrf5 == max_val

''' watch the solution live class... solution is to use unravel or mask filtering'''


[[0.54645587 0.95602551 0.69833229 0.89714837 0.01850543]
 [0.69055701 0.7307058  0.58176151 0.64150873 0.22621847]
 [0.50187583 0.10663974 0.61432911 0.63905411 0.73668551]
 [0.11175016 0.61875061 0.85056975 0.89944792 0.17506716]
 [0.99469617 0.45985712 0.59564472 0.22429319 0.18292509]]
20


IndexError: index 20 is out of bounds for axis 1 with size 5

In [144]:
## Numpy-FF7: Given the following NumPy code, predict the output of the code:

import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = A[1:3, 0:2]

'''
B will be
 [100, 5]
 [7, 8]
'''

B[0, 0] = 100

'''
I thought the answer will be following, how did it change the value of A matrix
[ 1 2 4 ]
[ 4 5 6 ]
[ 7 8 9 ]
'''
print(A)

print(B)
'''
If you do slicing, you are actually looking at the original array...  so here B is a view of A , so the
if reference is same:
'''
B = A[1:3, 0:2]  ## B is a view.... this is same as B=A[1:3, 0:2].view()

C = A[1:3, 0:2].copy() ## this gives a new array. not view. so answer will be different as expected.
print(A)
print(B)
print(C)


[[  1   2   3]
 [100   5   6]
 [  7   8   9]]
[[100   5]
 [  7   8]]
[[  1   2   3]
 [100   5   6]
 [  7   8   9]]
[[100   5]
 [  7   8]]
[[100   5]
 [  7   8]]


In [160]:
## Numpy-FF8: Write a Python program using NumPy to create a 1D array of 20 elements with random integers between 1 and 100. Calculate the number of even and odd elements in the array and print the result.

#arr_x = np.random.randint(1,101,20).reshape(1,-1)
arr_x = np.random.randint(1,101,20)

print(arr_x)

even_arr = arr_x[arr_x %2 == 0]
print("Number of even numbers in the array:", len(even_arr))

odd_arr = arr_x[arr_x %2 != 1]
print("Number of odd numbers in the array:", len(odd_arr))

print(len(arr_x[arr_x % 2 == 0]))
print(len(arr_x[arr_x % 2 == 1]))

#Alternate solution
print(arr_x % 2)
print(np.count_nonzero(arr_x % 2 == 0)) #Even numbers
print(np.count_nonzero(arr_x % 2 == 1)) #Odd numbers

#Alternate solution
print(len(np.where(arr_x %2 == 0)[0]))
print(len(np.where(arr_x %2 == 1)[0]))

[54 41 75 46 63 50 30 83 42 92 85 41 35 21 20  8 40 90 84 98]
Number of even numbers in the array: 12
Number of odd numbers in the array: 12
12
8
[0 1 1 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0]
12
8
12
8


In [109]:
## Numpy-FF9: Given the following NumPy code, predict the output of the code:

import numpy as np

A = np.arange(1, 17).reshape(4, 4)
B = A[:, ::-1]

''' Didn't understand... instructor review'''
'''
just ":" ---> this means everyting... all rows and column_stack
"::-1"   ---> this means reversing,, first col will be last and last will be first.

so Rows haven't changed, the columns got reversed.
'''
print(B)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [163]:
## Numpy-FF10: Write a Python program using NumPy to create a 2D array of size 8x8, where the outer border elements are set to 1 and the inner elements are set to 0. Print the resulting array.

import numpy as np

arr_y = np.ones((8,8))
arr_y[1:7, 1:7]=0
print(arr_y)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])